### ISSUE TITLE
Syntax error: "(" unexpected`

### ISSUE THREAD

**Issue by freezable** [AllysonSilva/php-pre-commit#1]
1. make code changes
2. add files to git (git add)
3. make commit (git commit -m 'test')

**result:** Error message:
`.git/hooks/pre-commit: 128: .git/hooks/pre-commit: Syntax error: "(" unexpected`

**Comment by paseto** [comment]
Replace `#!/bin/sh`
To `#!/bin/bash`

**Comment by Nayunis** [comment]
Hi paseto, 
thanks for your answer. Would you be able to clarify where this needs to be replaced and why?
I have the same problem as freezable, but couldn't figure out where i need to put the #!bin/bash

thanks!
